[package]
name = "rust_http_echo_over_tokio"
version = "0.1.0"
authors = ["Smotrov Dmitriy <smotrov@worksolutions.ru>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
