---

- docker_container:
    name: "openvpn"
    image: "kylemanna/openvpn"
    pull: true
    state: started
    recreate: yes
    restart_policy: always
    ports:
      - "1194:1194/udp"
    capabilities:
      - "NET_ADMIN"
    volumes:
      /opt/openvpn:/etc/openvpn
