// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package main

type StringStringDictionary struct {
	items map[string]string
}

type StringIntDictionary struct {
	items map[string]int
}

type IntStringDictionary struct {
	items map[int]string
}

type IntIntDictionary struct {
	items map[int]int
}
