---

- docker_container:
    name: "socks5"
    image: "serjs/go-socks5-proxy"
    state: started
    recreate: yes
    restart_policy: always
    ports:
      - "1080:1080"
    env:
      PROXY_USER: user
      PROXY_PASSWORD: password
