version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/var/lib/mysql
      - ./mariadb.cnf:/etc/mysql/mariadb.conf.d/mariadb.cnf
    ports:
      - "11000:3306"
    restart: always

  sources:
    build: sources
    volumes:
      - ./sources/www:/var/www/html
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
        XDEBUG_CONFIG: remote_host=192.168.1.224